apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ksql.name" . }}-configmap
  labels:
    app: "{{ template "ksql.name" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
data:
  ksqlserver.properties: |-
    bootstrap.servers={{ .Values.kafka.host }}:{{ .Values.kafka.port }}
    ksql.command.topic.suffix=commands
    listeners=http://localhost:8088
    ui.enabled=true
    ksql.cluster.id=datagram
    application.id=datagram
