{{- if .Values.datagen.enabled -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f /home/avigershon/projects/ksql/docs/quickstart/docker-compose.yml
      convert
    kompose.version: 1.9.0 (093c756)
  creationTimestamp: null
  labels:
    io.kompose.service: ksql-datagen-pageviews
  name: ksql-datagen-pageviews
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: ksql-datagen-pageviews
    spec:
      containers:
      - args:
        - bash
        - -c
        - echo Waiting for Kafka to be ready... && cub kafka-ready -b kafka:9092
          1 20 && echo Waiting for Confluent Schema Registry to be ready... && cub
          sr-ready kafka-schema-registry 8081 20 && echo Waiting a few seconds for topic
          creation to finish... && sleep 2 && java -jar /usr/share/java/ksql-examples/ksql-examples-4.1.0-SNAPSHOT-standalone.jar
          quickstart=pageviews format=delimited topic=pageviews bootstrap-server=kafka:9092
          maxInterval=1000 iterations=1000 && java -jar /usr/share/java/ksql-examples/ksql-examples-4.1.0-SNAPSHOT-standalone.jar
          quickstart=pageviews format=delimited topic=pageviews bootstrap-server=kafka:9092
          maxInterval=10000
        env:
        - name: KSQL_CONFIG_DIR
          value: /etc/ksql
        - name: KSQL_LOG4J_OPTS
          value: -Dlog4j.configuration=file:/etc/ksql/log4j-rolling.properties
        - name: STREAMS_BOOTSTRAP_SERVERS
          value: kafka:9092
        - name: STREAMS_SCHEMA_REGISTRY_HOST
          value: kafka-schema-registry
        - name: STREAMS_SCHEMA_REGISTRY_PORT
          value: "8081"
        image: confluentinc/ksql-examples:0.5-rc0
        name: ksql-datagen-pageviews
        resources: {}
      restartPolicy: Always
status: {}
{{- end -}}
